version: "3.7"
services:
  server:
    build: .
    restart: always
    ports:
      - 8082:8081
    depends_on:
      - mysqldb
  mysqldb:
    platform: linux/x86_64
    image: "mysql:8.0.29"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: blog_db
      MYSQL_ROOT_PASSWORD: ikechi
      MYSQL_ROOT_USERNAME: ikechi