version: "3.8"
services:
### Postgres Database ###
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blog_db
#      - PGDATA=/var/lib/postgresql/data/pgdata
#    volumes:
#      - pgdata:/var/lib/postgresql/data
    restart: always
### Postgres PgAdmin ###
  postgres_admin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    restart: always
### API Spring Boot ###
  server:
    container_name: appserver
    image: iykeafrica/blog-dockerized
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/blog_db
    ports:
      - "8081:8081"
    restart: always