name: CI
on:
  push:
    branches:
      -  "fashion-blog-cicd"
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ikechi
          MYSQL_DATABASE: blog_db
        ports:
          - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - run: mysql --host 127.0.0.1 --port 32574 -uroot -ppassword -e 'CREATE DATABASE IF NOT EXISTS blog_db;'

      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'adopt'
      - name: setup Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2
      - name: run compile
        run: mvn clean install