name: ci

on:
  push:
    branches:
      - 'cicd'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2

#      - name: Build the stack
#      - uses: actions/checkout@v2
#        run: docker-compose up -d

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          image: iykeafrica/blog-dockerized
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}