name: CI
on:
  push:
    branches:
      -  "fashion-blog-cicd"
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_USER: ikechi
          MYSQL_PASSWORD: ikechi
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: blog_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - run: mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e 'CREATE DATABASE IF NOT EXISTS blog_db;'
      - run: mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e 'CREATE USER IF NOT EXISTS 'ikechi'@'localhost' IDENTIFIED BY 'ikechi';'
      - run: mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e 'GRANT ALL PRIVILEGES ON blog_db.* TO 'ikechi'@'localhost';'

      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'adopt'
      - name: setup Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2
      - name: run compile
        run: mvn clean install

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: iykeafrica/my-fashion-blog
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}